
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:3000
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
            maxAge: 3600
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   
      routes:
      - id: ShoppingMS
        predicates:
        - Path=/api/shoppingservice/**
        uri: lb://ShoppingMS
      - id: Cart-MS
        predicates:
        - Path=/cart/**
        uri: lb://Cart-MS
      - id: CUSTOMER-MS
        predicates:
        - Path=/customer/**
        uri: lb://CUSTOMER-MS
      - id: Inventory-MS
        predicates:
        - Path=/inventory/**
        uri: lb://Inventory-MS
      - id: Order-MS
        predicates:
        - Path=/order/**
        uri: lb://Order-MS
      - id: Products-MS
        predicates:
        - Path=/product/**
        uri: lb://Products-MS
